package service;g

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class KlientManager {
	private Connection connection;
	private String url =  "jdbc:hsqldb:hsql://localhost/workdb";
	private String createTableKlient = "CREATE TABLE Klient(id_klient bigint GENERATED BY DEFAULT AS IDENTITY, imie varchar(30), nazwisko varchar(50),telefon bigint)"; 
	
	
	private PreparedStatement DodajKlient;
	private PreparedStatement UsunKlienta;
	private PreparedStatement UsunKlientow;
	private PreparedStatement PobierzKlientow;
	private PreparedStatement EdytujKlienta;
	
	private Statement statement;
	
	public KlientManager(){
		try(
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();
			
			ResultSet rs =	connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while(rs.next()){
				if("Klient".equalsIgnoreCase(rs.getString("TABLE_NAME"))){
					tableExists = true;
					break;
				}
			}
			
			if(!tableExists)
				statement.executeUpdate(createTableKlient);
			
			DodajKlient = connection.prepareStatement("INSERT INTO Klient(imie, nazwisko, telefon) VALUES (?, ?, ?)");
			UsunKlient = connection.prepareStatement("DELETE FROM Klient WHERE id_klient = ?");
			UsunKlientow = connection.prepareStatement("DELETE FROM Klient");
			PobierzKlientow = connection.prepareStatement("SELECT id_klient, imie, nazwisko, telefon FROM Klient");
			EdytujKlienta = connection.prepareStatement("UPDATE Klient SET imie = ?, nazwisko = ?, telefon = ? WHERE id_klient = ?");
			
				
			
	}catch(SQLException e){
		e.printStackTrace();
	}
}

Connection getConnection(){
	return connection;
}
	void wyczyscKlientow(){
	try{
		UsunKlientow.executeUpdate();
		}catch (SQLException e){ 
			e.printStackTrace();
		}
}

	public int DodajKlienta(Klient klient){
		int count = 0;
		try{
			DodajKlienta.setString(1, klient.getImie());
			DodajKlienta.setString(2, klient.getNazwisko());
			DodajKlienta.setLong(3, klient.getTelefon());
			
			
			
			count = DodajKlienta.executeUpdate();
			
			
		}catch (SQLException e){
			e.printStackTrace();
		}
		return count;
	}
	public List<Klient> PobierzKlientow(){
		List<Klient> klienci = new ArrayList<Klient>();
		
		try{
			ResultSet re = PobierzKlientow.executeQuery();
			
			while (rs.next()){
				Klient k = new Klient();
				k.setId_klient(rs.getLong("id_klient"));
				k.setImie(rs.getImie("imie"));
				k.setNazwisko(rs.getNazwisko("nazwisko"));
				k.setTelefon(rs.getTelefon("telefon"));
				klient.add(k);
			}catch(SQLException e) {
				e.printStackTrace();
			}
			return klient;
		}
	}