


package service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import main.SprzedazKarnetu;

public class SprzedazKarnetuManager {
	private Connection connection;
	private String url =  "jdbc:hsqldb:hsql://localhost/";
	private String createTableSprzedazKarnetu = "CREATE TABLE SprzedazKarnetu(id_sprzedazKarnetu bigint GENERATED BY DEFAULT AS IDENTITY, id_klient long, id_karnet long, cena double, notatka varchar(500))"; 
	
	
	private PreparedStatement DodajSprzedazKarnetu;
	private PreparedStatement UsunSprzedazKarnetu;
	private PreparedStatement UsunSprzedazeKarnetu;
	private PreparedStatement PobierzSprzedazeKarnetu;
	private PreparedStatement EdytujSprzedazKarnetu;
	
	private Statement statement;
	
	public SprzedazKarnetuManager(){
		try{
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();
			
			ResultSet rs =	connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while(rs.next()){
				if("SprzedazKarnetu".equalsIgnoreCase(rs.getString("TABLE_NAME"))){
					tableExists = true;
					break;
				}
			}
			
			if(!tableExists)
				statement.executeUpdate(createTableSprzedazKarnetu);
			
			DodajSprzedazKarnetu = connection.prepareStatement("INSERT INTO SprzedazKarnetu(id_klient, id_karnet, notatka) VALUES (?, ?, ?)");
			UsunSprzedazKarnetu = connection.prepareStatement("DELETE FROM SprzedazKarnetu WHERE id_SprzedazKarnetu = ?");
			UsunSprzedazeKarnetu = connection.prepareStatement("DELETE FROM SprzedazKarnetu");
			PobierzSprzedazeKarnetu = connection.prepareStatement("SELECT id_klient, id_karnet, notatka FROM SprzedazKarnetu");
			EdytujSprzedazKarnetu = connection.prepareStatement("UPDATE SprzedazKarnetu SET id_klient = ?, id_karnet = ?, notatka = ? WHERE id_SprzedazKarnetu = ?");
			
				
			
	}catch(SQLException e){
		e.printStackTrace();
	}
}

public Connection getConnection(){
	return connection;
}
	public void wyczyscSprzedazeKarnetu(){
	try{
		UsunSprzedazeKarnetu.executeUpdate();
		}catch (SQLException e){ 
			e.printStackTrace();
		}
}

	public int dodajSprzedazKarnetu(SprzedazKarnetu sprzedazKarnetu){
		int count = 0;
		try{
			DodajSprzedazKarnetu.setLong(1, SprzedazKarnetu.getId_klient());
			DodajSprzedazKarnetu.setLong(2, SprzedazKarnetu.getId_karnet());
			DodajSprzedazKarnetu.setString(3, SprzedazKarnetu.getNotatka());
			
			
			
			count = DodajSprzedazKarnetu.executeUpdate();
			
			
		}catch (SQLException e){
			e.printStackTrace();
		}
		return count;
	}
	
	public int edytujSprzedazKarnetu(SprzedazKarnetu sprzedazKarnetu){
		int count = 0;
		try{
		
			EdytujSprzedazKarnetu.setLong(1, sprzedazKarnetu.getId_klient());
			EdytujSprzedazKarnetu.setLong(2, sprzedazKarnetu.getId_karnet());
			EdytujSprzedazKarnetu.setString(3, sprzedazKarnetu.getNotatka());
			EdytujSprzedazKarnetu.setLong(4, sprzedazKarnetu.getId_karnet());
			
			
			count = EdytujSprzedazKarnetu.executeUpdate();
			
			
		}catch (SQLException e){
			e.printStackTrace();
		}
		return count;
	}
	public int usunSprzedazKarnetu(SprzedazKarnetu sprzedazKarnetu){
		int count = 0;
		try{
			UsunSprzedazKarnetu.setLong(1, sprzedazKarnetu.getId_sprzedazKarnetu());

			
			
			
			count = UsunSprzedazKarnetu.executeUpdate();
			
			
		}catch (SQLException e){
			e.printStackTrace();
		}
		return count;
	}
	
	
	public List<SprzedazKarnetu> SprzedazKarnetu(){
		List<SprzedazKarnetu> sprzedazeKarnetu = new ArrayList<SprzedazKarnetu>();
		
		try{
			ResultSet rs = PobierzSprzedazeKarnetu.executeQuery();
			
			while (rs.next()){
				SprzedazKarnetu s = new SprzedazKarnetu();
				s.setId_klient(rs.getLong("id_klient"));
				s.setId_karnet(rs.getLong("id_karnet"));
				s.setNotatka(rs.getString("notatka"));
				
				sprzedazeKarnetu.add(s);
			}}catch(SQLException e) {
				e.printStackTrace();
			}
			return sprzedazeKarnetu;
		}
	}